### PR TITLE
[tests only] Mocks for handlers

### PR DESCRIPTION
**Pull request by kulmann**
We need to be able to mock our service handlers in tests (at the moment needed in ocis-proxy)

### CODE REVIEW

**Comment by individual-it** [comment]
why not just start the depending service?

**Comment by kulmann** [comment]
> why not just start the depending service?

For unit tests

**Comment by IljaN** [comment]
Imo starting the depending service could be also a valid approach even for "unit-tests" if you see proxy and accounts-service as one unit. Ofcourse this will impact test-runtime etc...

**Comment by kulmann** [comment]
I don't agree. I want to run quick tests in my IDE all the time, so that I can find issues early. Those should not depend on a separate service.

**Review by butonic — APPROVED** [review]

**Pull request merged**
