### PR TITLE
Clean up paths in makefile

### PR DESCRIPTION
**Pull request by kulmann**
Stumbled upon paths in Makefile where we could use an already existing variable

### CODE REVIEW

**Comment by kulmann** [comment]
No, that's still [this issue](https://github.com/owncloud/ocis-settings/issues/30) and unrelated to this PR :-( restarted CI... really have to look into that failures

**Comment by kulmann** [comment]
@micbar CI is green now

**Comment by phil-davis** [comment]
I restarted CI. Due to the GitHub downtime the drone CI status did not update.

**Comment by phil-davis** [comment]
Sadly the status still did not update. Drone CI https://cloud.drone.io/owncloud/ocis-settings/133 passed.

**Pull request merged**
