### PR TITLE
Allow any user id format

### PR DESCRIPTION
**Pull request by PVince81**
The user id / account UUID should allow any format as in some cases a regular user name
could be used there.

Fixes https://github.com/owncloud/ocis-settings/issues/41

- [x] local test with Phoenix

### CODE REVIEW

**Comment by PVince81** [comment]
confirmed that all the Phoenix tests I ran locally are passing now, because there is no more interference due to the error that was shown.

**Comment by phil-davis** [comment]
Note: in core we can create usernames (which in core are userid also) according to this restriction:
```
Error creating user: Only the following characters are allowed in a username: "a-z", "A-Z", "0-9", and "+_.@-'"
```
There are usernames that have `+` in them, and certainly ones that have `.` and `@`

I don't know if that makes any difference here. Maybe the username can happily be `phil+jenny.davis@abc` and the user id will be something else.

**Comment by PVince81** [comment]
@kulmann might be better to adjust the formats right away to avoid future surprises and time lost debugging ?

**Comment by kulmann** [comment]
Yes, I agree. Adapting it now...

**Pull request merged**
